// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Products;

#nullable disable

namespace Products.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20230504210722_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shared.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Isin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b8aed924-935f-4acc-96d8-9776f521351c"),
                            Isin = "DE00SWWU7HPV",
                            Price = 967.704472196563960m,
                            Title = "Denesik, Zieme and Douglas"
                        },
                        new
                        {
                            Id = new Guid("30d3d748-84cd-4126-93cf-9ad9d38347e0"),
                            Isin = "DE00315JY9X7",
                            Price = 34.8890010860049130m,
                            Title = "Cassin - Hamill"
                        },
                        new
                        {
                            Id = new Guid("b3db6a47-850d-434c-b417-d2756a7b4578"),
                            Isin = "DE009J6Z0LLD",
                            Price = 92.3625567435425590m,
                            Title = "Toy, Blick and Schoen"
                        },
                        new
                        {
                            Id = new Guid("f6914d50-6478-4232-9d7d-65942cb6ad80"),
                            Isin = "DE00UN5VEVOE",
                            Price = 472.517687575705960m,
                            Title = "Quitzon Inc"
                        },
                        new
                        {
                            Id = new Guid("f5947ec4-d3e0-45b5-9b7b-2807f980e530"),
                            Isin = "DE00O46S87DR",
                            Price = 565.617849190565590m,
                            Title = "Kautzer LLC"
                        },
                        new
                        {
                            Id = new Guid("3960d4dd-274c-4e54-ba0e-bc3b637ec7fc"),
                            Isin = "DE00757D8Q5D",
                            Price = 574.118450664372010m,
                            Title = "Shields and Sons"
                        },
                        new
                        {
                            Id = new Guid("5e233ecf-c3a1-4fba-baef-885e505dcaa4"),
                            Isin = "DE00MA9S3BFJ",
                            Price = 211.613140234917730m,
                            Title = "Schinner, Hilll and Denesik"
                        },
                        new
                        {
                            Id = new Guid("1cc1aa39-dee5-4a5a-94c3-821ccfd2806a"),
                            Isin = "DE00R63EBL9L",
                            Price = 360.842036462723080m,
                            Title = "Schowalter, Botsford and Frami"
                        },
                        new
                        {
                            Id = new Guid("0d0cba07-3475-4b62-bc2e-ba5f2e13fe2c"),
                            Isin = "DE00XF72D6Y4",
                            Price = 167.841819268374340m,
                            Title = "Thompson, Goyette and Romaguera"
                        },
                        new
                        {
                            Id = new Guid("614abe09-ca79-4426-a1df-837f677faf44"),
                            Isin = "DE006OBNO29U",
                            Price = 499.5431002553410m,
                            Title = "Block Inc"
                        },
                        new
                        {
                            Id = new Guid("f3999491-8a38-46ec-baaf-891bf8cd3fe3"),
                            Isin = "DE00VI1KMJ0D",
                            Price = 508.124667141811270m,
                            Title = "Mante, Paucek and Kertzmann"
                        },
                        new
                        {
                            Id = new Guid("63317d37-9198-409e-8c71-87b902a298c0"),
                            Isin = "DE00YJR4I23V",
                            Price = 615.808702795151350m,
                            Title = "Hirthe LLC"
                        },
                        new
                        {
                            Id = new Guid("7ffd0b7e-81b3-4499-9da7-6310cfa6f216"),
                            Isin = "DE00YDGV6TD6",
                            Price = 837.49883761073980m,
                            Title = "Greenholt - Ondricka"
                        },
                        new
                        {
                            Id = new Guid("6727b4e3-fdf8-4eeb-937c-c872e8f93db8"),
                            Isin = "DE0095V3LZZR",
                            Price = 810.557975668218130m,
                            Title = "Nader - Beahan"
                        },
                        new
                        {
                            Id = new Guid("5c9990ac-ff69-4ba6-bcb9-9bd1d908803d"),
                            Isin = "DE00VR9U7V5N",
                            Price = 348.200917795951210m,
                            Title = "Altenwerth and Sons"
                        },
                        new
                        {
                            Id = new Guid("9a67ba95-2df7-44dd-b444-194af96d0e36"),
                            Isin = "DE00PVUWGE67",
                            Price = 531.743022308992330m,
                            Title = "Kshlerin Group"
                        },
                        new
                        {
                            Id = new Guid("23914259-ba1d-4c9a-a94e-22db6fa3c6b8"),
                            Isin = "DE00U4E4664K",
                            Price = 920.346896981999620m,
                            Title = "Abbott, Feeney and Koelpin"
                        },
                        new
                        {
                            Id = new Guid("5882c705-2e9d-45f5-b4be-080c1a4815c4"),
                            Isin = "DE00E5V2891S",
                            Price = 16.25582765740828060m,
                            Title = "Berge - Jerde"
                        },
                        new
                        {
                            Id = new Guid("2a402d39-3cb1-450a-9057-ae0081c16049"),
                            Isin = "DE000PVZ00QY",
                            Price = 677.349042834036970m,
                            Title = "Hamill LLC"
                        },
                        new
                        {
                            Id = new Guid("5e8a2747-ab57-4c71-90ba-57244de9ba88"),
                            Isin = "DE00LU2S9UG6",
                            Price = 544.665654871025590m,
                            Title = "Casper and Sons"
                        },
                        new
                        {
                            Id = new Guid("2a810d45-882d-4279-8092-a5fee4f31691"),
                            Isin = "DE00KD0HPWCB",
                            Price = 766.329395152307680m,
                            Title = "Sipes, Greenholt and Champlin"
                        },
                        new
                        {
                            Id = new Guid("aaf1ef4c-f248-4260-833e-6447f0c523e1"),
                            Isin = "DE00607R4DC6",
                            Price = 182.759286513920590m,
                            Title = "Bernhard, Kunze and Oberbrunner"
                        },
                        new
                        {
                            Id = new Guid("8e711d26-e8f2-49f9-812b-77bc21172c7a"),
                            Isin = "DE00CR1213E3",
                            Price = 618.21058415693950m,
                            Title = "Lockman and Sons"
                        },
                        new
                        {
                            Id = new Guid("c728db82-81a3-48f8-a522-a211bb9a2972"),
                            Isin = "DE00K6E02259",
                            Price = 724.57966693718110m,
                            Title = "Kuphal and Sons"
                        },
                        new
                        {
                            Id = new Guid("03b9eb7c-e3e4-4fa2-8369-cf330387c9ce"),
                            Isin = "DE00N5N6OP4H",
                            Price = 763.394181566851990m,
                            Title = "Hills - Tillman"
                        },
                        new
                        {
                            Id = new Guid("60b5bfec-f8e6-4592-8be3-bed9e254afc2"),
                            Isin = "DE00F1474TZ2",
                            Price = 493.72944490833490m,
                            Title = "Schaden - Rolfson"
                        },
                        new
                        {
                            Id = new Guid("17af5ff4-10a2-498d-a562-60562c20071b"),
                            Isin = "DE00C7YRQ00I",
                            Price = 349.626823238713780m,
                            Title = "Champlin Inc"
                        },
                        new
                        {
                            Id = new Guid("ba6a1887-c2b6-4d1a-84d6-c2737a19d40e"),
                            Isin = "DE006W43N0OK",
                            Price = 772.556018532670450m,
                            Title = "Koepp and Sons"
                        },
                        new
                        {
                            Id = new Guid("fd9dcb51-9592-46b0-9930-f52cf8c836a3"),
                            Isin = "DE00U11I7T92",
                            Price = 621.611164553539150m,
                            Title = "Yundt - Rowe"
                        },
                        new
                        {
                            Id = new Guid("841a69de-53c6-4ee8-8d46-94697e95e512"),
                            Isin = "DE00O9QH4PP9",
                            Price = 359.885726723255140m,
                            Title = "Emmerich and Sons"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
